### PR TITLE
[OLD] Added resizable crop feature

### LINKED ISSUE #15: Custom rectangular shape crop
Hi!
Are there any plans to make the cropper to take a custom rectangular shape, rather than a simple square? Also, it would great to add the ability to rotate an image (like in "Edit" mode in "Photos" app).

### PR DESCRIPTION
**Pull request by Tulleb**
Also deleted default Team ID.

Closes #15.
Update of #125.

### CODE REVIEW

**Comment by ameli90** [comment]
it would be good to set minimum area to crop

**Comment by AlexLittlejohn** [comment]
Thank you for creating this and apologies for taking so long to get back to you about it.

**Comment by Tulleb** [comment]
@AlexLittlejohn Well at the moment, the origin cropping area is still a square that the user can pan. But if you want developers to be able to forbid users from resizing the crop area, then yes we need to add something. I am quite busy at the moment, I will do it asap.

**Comment by Fengson** [comment]
Like I mentioned in a commet for issue #15 :

`
Just to let you know, cropping @Tulleb doesn't work well.
There should be a constraint that prevents moving the overlay outside of the image bounds. 
Otherwise, many issues arise and cropping doesn't work if overlay consists of the area outside of the image bounds. And you can never expect what a user would do :)
`

**Comment by Tulleb** [comment]
So what is left to do for this PR:
- Add an option which disable the feature by default.
- Prevent user to crop outside of the image bounds.

I will try to work on it on the next few weeks if @AlexLittlejohn is still interested.

**Comment by AlexLittlejohn** [comment]
@Tulleb I'm definitely interested in having these features available. Send me a PM if you need a hand.

**Comment by Tulleb** [comment]
Anything for a Dota 2 player @AlexLittlejohn ^^
I should start to work on it this weekend.

**Comment by Tulleb** [comment]
I will make a new PR rebased on your current master. This one will be obsolete.

**Pull request closed without merging**
