### PR TITLE
Added resizable cropping area feature

### LINKED ISSUE #15: Custom rectangular shape crop
Hi!
Are there any plans to make the cropper to take a custom rectangular shape, rather than a simple square? Also, it would great to add the ability to rotate an image (like in "Edit" mode in "Photos" app).

### PR DESCRIPTION
**Pull request by Tulleb**
**This PR add the resizable cropping area feature.**

Closes #15.
Update of #192.

It also:
- Removed the default Team ID.
- Changed the view order into Confirmation View in order to always be able to tap on confirm & cancel buttons.
- Added an option to disable the feature.
- Defined a minimum area to crop (@ameli90) and added an option to change it.

Left to do later on:
- Prevent user to crop outside of the image bounds.

### CODE REVIEW

**Comment by Tulleb** [comment]
@AlexLittlejohn I was wondering about the cropping resize being disabled by default.

I agree that it may disturb your current user base, but in my opinion, most of your users will want this feature activated by default. Therefor, I think an option should be propose not to prevent it, but not activated by default.

Maybe a warning in your futur release note pointing out this feature and showing out how to disable it would be enough?

Tell me. I will add this option anyway (but disabled by default for the moment).

**Comment by AlexLittlejohn** [comment]
@Tulleb The alternative is that we just do a major version release with the breaking change

**Comment by Tulleb** [comment]
@AlexLittlejohn Up to you ;)

**Comment by AlexLittlejohn** [comment]
@Tulleb Feels like it's time for a v2.0.0 🥇

**Comment by Tulleb** [comment]
Ready to merge @AlexLittlejohn!

I didn't have enough time to do add the "Prevent user to crop outside of the image bounds" feature, sorry. Maybe next time.

**Comment by Fengson** [comment]
I'm sorry, but I feel "Prevent user to crop outside of the image bounds" is the only feature worth a pull request. Without it, the changes are very minor.

Any chance to add it, @Tulleb ?

**Comment by Tulleb** [comment]
Hi @Fengson, could you then submit a new issue to talk more about the problem since it is now merged into Master?

I don't really understand the problem actually. When I am cropping outside of the image bounds, the result is what I expected most of the time. Can you give us some exemples?

Thank you.

**Comment by PankajGaikar** [comment]
Kudos.

**Pull request merged**
