### PR TITLE
Rotate Screen

### PR DESCRIPTION
**Pull request by ppamorim**
Big changes at all. Now, `CameraView` can rotate the layer and any button of `CameraViewController` will rotate when you rotate the screen.
Btw, what do you think, when the device is landscape, to move the close button to bottom of gallery button? I think it is more concise and maintain the flow of the layout. It is better to use with tablets too.

### CODE REVIEW

**Comment by ppamorim** [comment]
Fixing layout error with crop view.

**Comment by ppamorim** [comment]
Trying to fix the conflicts

**Comment by ppamorim** [comment]
@AlexLittlejohn Fixed! Can you verify?

**Comment by ppamorim** [comment]
I have discovered a new problem with orientation, fixing...

**Comment by ppamorim** [comment]
I removed this code:

https://github.com/AlexLittlejohn/ALCameraViewController/blob/develop/ALCameraViewController/ViewController/CameraViewController.swift#L158

Why? This can break the AutoLayout constraints, you need to setup the margin/padding with the constraint configuration, like:

```swift
 //The padding between the left of the superview and the left of someView.
let padding : CGFloat = 16.0

view.addConstraint(NSLayoutConstraint(
                item: someView,
                attribute: .Left,
                relatedBy: .Equal,
                toItem: view,
                attribute: .Left,
                multiplier: 1.0, 
                constant: padding))
```

**Comment by ppamorim** [comment]
img_0144

Look this... After the rotation of the view, the layout was moved to a wrong way, caused by the margin. The `SwapButton` constraint was ignored and this property forced to push this view to left.

**Comment by ppamorim** [comment]
I have this layout running on a iPhone 4S today, what do you think about? Do you want to add a bigger spacing (16.0px) between the top | right side of the `FlashButton` when portrait?

img_0140 img_0146

**Comment by AlexLittlejohn** [comment]
Hmm, i'm not a huge fan of that rotation, I believe an approach that more closely resembles the built in camera is the way to go. (The way it is currently)

**Comment by ppamorim** [comment]
It's a design fault for me. You are forcing the device to rotate something that is not rotated. It will be confuse if the user receive a notification or  open the bottom configuration menu, both are open with a incorrect orientation of the device. At first, any menu will open rotated 90º degress, it's ugly.

**Comment by ppamorim** [comment]
@AlexLittlejohn Can you check this changes, I need to implement the animation rotation of the items on the screen. But the screen don't rotate anymore. :100:

**Comment by AlexLittlejohn** [comment]
Ive taken a look and its almost there, my only concern is the positioning of the library button. It no longer pins itself to the screen edge on bigger iOS Devices like the 6s and the 6s+ so it looks misaligned. Perhaps if we move the swap button to the top left we can align the library button with the flash button. Thoughts?

**Comment by ppamorim** [comment]
Offtopic: What do you think to move these methods of config constraints to a another file? We could use extension to do it.

**Comment by AlexLittlejohn** [comment]
Read my mind :smile:, The `CameraViewController` is over 1000 lines now. Definitely a good idea to factor out the constraints.

**Comment by ppamorim** [comment]
We don't need to move the `SwapButton` to correct the `LibraryButton`. To fix this problem is very simple! We need to detect if the device is >= iPhone 6 and pin the right of `LibraryButton` on the right of superview.

**Comment by ppamorim** [comment]
@AlexLittlejohn Do you want to exactly pin the `LibraryButton` on the right or create a center-relation between the `LibraryButton` and `SwapButton`? It will be more difficult to create, but it is possible.

**Comment by AlexLittlejohn** [comment]
Whichever is simplest. I think that just pinning the library button will create the desired effect on larger phones.

**Comment by ppamorim** [comment]
@AlexLittlejohn I'm working with a lot of projects right now, but I'm trying to finish this feature.

**Comment by AlexLittlejohn** [comment]
@ppamorim No stress, contribution is for fun and enjoyment only.

**Comment by ppamorim** [comment]
@AlexLittlejohn Can you check?

**Comment by ppamorim** [comment]
?

**Comment by AlexLittlejohn** [comment]
@ppamorim i've just been a little swamped these past few days but I will definitely have a look in a few hours. From what i've seen so far it looks good though.

**Comment by AlexLittlejohn** [comment]
If you're happy with this then i'll merge it asap.

**Comment by ppamorim** [comment]
I need to check this approach on a tablet...

**Comment by AlexLittlejohn** [comment]
Tested on an iPad mini. Looks fine. Merging.

**Comment by ppamorim** [comment]
Oh thanks!

**Pull request merged**
